name: Update table
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  update_table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Download Go dependencies
        run: go mod download

      - name: Run script
        run: go run main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
          default_author: github_actions
          message: 'Update generated table'